[package]
name = "wzm-comp"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
bitflags = "2.2.1"
smithay.workspace = true
wzm-config.workspace = true
xkbcommon = "0.7.0"
nix = { version = "0.28.0" }
once_cell = "1.19.0"
cgmath = "0.18.0"
